MOVE /Y C:\Users\Toby_huang\Desktop\files\.env C:\Users\Toby_huang\laradock
MOVE /Y C:\Users\Toby_huang\Desktop\files\default.conf C:\Users\Toby_huang\laradock\nginx\sites
MOVE /Y C:\Users\Toby_huang\Desktop\files\iconkit.back.conf C:\Users\Toby_huang\laradock\nginx\sites
MOVE /Y C:\Users\Toby_huang\Desktop\files\iconkit.front.conf C:\Users\Toby_huang\laradock\nginx\sites
MOVE /Y C:\Users\Toby_huang\Desktop\files\project.management.conf C:\Users\Toby_huang\laradock\nginx\sites
MOVE /Y C:\Users\Toby_huang\Desktop\files\webbbin.back.conf C:\Users\Toby_huang\laradock\nginx\sites
MOVE /Y C:\Users\Toby_huang\Desktop\files\webbbin.front.conf C:\Users\Toby_huang\laradock\nginx\sites
MOVE /Y C:\Users\Toby_huang\Desktop\files\php7.2.ini C:\Users\Toby_huang\laradock\php-fpm
MOVE /Y C:\Users\Toby_huang\Desktop\files\my.cnf C:\Users\Toby_huang\laradock\mysql